name: Integrate Frontend

on:
    push:
        paths:
            - "Client/**"
        branches: ["main"]

    pull_request:
        paths:
            - "Client/**"
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./Client
        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                node-version: '20.x'
                cache: 'npm'
                cache-dependency-path: Client/package-lock.json
            
            - name: installing dependencies
              run: npm ci

            - name: building app
              run: npm run build

    sonar-scan:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./Client
        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                node-version: '20.x'
                cache: 'npm'
                cache-dependency-path: Client/package-lock.json
            
            - name: installing dependencies
              run: npm ci

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
              with:
                args:
                    -Dsonar.projectKey= ${{secrets.SONAR_PROJECT_KEY}}
            