name: Integrate Frontend

on:
    push:
        paths:
            - "Client/**"
        branches: ["main"]

    pull_request:
        paths:
            - "Client/**"
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./Client
        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                node-version: '20.x'
                cache: 'npm'
                cache-dependency-path: Client/package-lock.json
            
            - name: installing dependencies
              run: npm ci

            - name: building app
              run: npm run build

            - name: SonarQube Scan
              uses: SonarSource/sonarcloud-github-action@v2
              with:
                projectBaseDir: Client
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              
            



            